### PR TITLE
Menu branch try 2

### PR DESCRIPTION
**Pull request by ROlearyPro**
## Type of Change

- [x] styling 🎨

## Description

Created side with menu icons, each of which can later be given functionality.
## Motivation and Context

This menu starts off the project in terms of appearance, and will serve as the base of a future navigation menu. 
Related issue on project board: https://github.com/turingschool/tracker-crm-fe/issues/3
## Added Test?

  - 
- [ x ] No 🙅

Cypress seems to have issues with .ts files.

## Checklist:

- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Sgalvin36** [comment]
Looking through it, it looks good, especially since we're still working on establishing style. I see that you implemented cypress so that its installed, but I didn't see any tests for cypress. Are you still planning on adding some tests?

**Comment by ROlearyPro** [comment]
> Looking through it, it looks good, especially since we're still working on establishing style. Looking at the menu bar layout, there are a lot of errors being raised by TypeScript about the .png's that you're using. Not sure if that's something that is an easy fix, but it is a potential bug to fix. I see that you implemented cypress so that its installed, but I didn't see any tests for cypress. Are you still planning on adding some tests?

Unfortunately, I'm running into an error in those regards that I'm unsure how to resolve; I'm receiving this error, and while I tried to search online for solutions, I wasn't able to find much. If you or anyone else can figure out what's causing this message, and a way to fix it without making everyone else refactor the whole project, I'd love to know; just ping me in slack, and we can find some time to speak.
Screenshot 2024-12-06 at 1 21 05 PM

**Comment by jimmacur** [comment]
I agree with Shane's comments that the style looks great - a great start.
Screenshot 2024-12-06 at 3 48 19 PM

Also, I figured out the TS errors for the png's.

Needs two updates

1) New file called `global.d.ts` in src that holds this

```
declare module '*.png' {
  const value: string;
  export default value;
}
```

2) add two options to the `tsconfig.json`

`"esModuleInterop": true`
`"allowSyntheticDefaultImports": true`

These additions should solve that issue.

**Comment by jimmacur** [comment]
On a separate note - why are there duplicate files in the `_site` and `src` 


Duplicate files include: 
- package-lock.json
- package.json
- postcss.config.js
- README.md
- tailwind.config.js
- tsconfig.bck.json
- tsconfig.json

**Comment by ROlearyPro** [comment]
> On a separate note - why are there duplicate files in the `_site` and `src` 


Those were there when I pulled this whole thing down from main. Honestly, I could delete them, if necessary, but I'd rather not until I know for sure that won't break something.

**Comment by jimmacur** [comment]
I was still seeing the TS error without these additions to the tsconfig.json

```
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
```

1 test block is looking good. The second one has clickable links. Is it safe to assume that those links will be replaced by the routes to the site as we move forward

**Comment by jimmacur** [comment]
Looks like the TS notifications I was seeing might be personal to my local. Merging!

**Pull request merged**
